language: elixir

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y graphviz

matrix:
  include:
    - otp_release: 21.2
      elixir: 1.6.6
    - otp_release: 23.2.5
      elixir: 1.11

script:
  - "MIX_ENV=test mix do deps.get, credo, coveralls.travis"
